services:
  artwork:
    build:
      context: .
      dockerfile: ./dockerfiles/release.Dockerfile
    depends_on:
      - db
    ports:
      - '${APP_PORT:-80}:80'
      - '${PUSHER_PORT:-6001}:6001'
      - '${PUSHER_METRICS_PORT:-9601}:9601'
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "artwork-files:/var/www/html/storage"
      - './.env:/var/www/html/.env'
  db:
    image: 'mariadb'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'artwork-db-maria5:/var/lib/mysql'
  meili:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'artwork-meilisearch:/data'
  redis:
    image: 'redis:alpine'
    volumes:
      - 'artwork-redis:/data'
volumes:
  artwork-db-maria5:
    driver: local
  artwork-meilisearch:
    driver: local
  artwork-redis:
    driver: local
  artwork-files:
    driver: local
