<?php

namespace Artwork\Modules\Event\Enum;

enum ShiftPlanWorkerSortEnum: string
{
    case ALPHABETICALLY_ASCENDING_FIRST_NAME = 'ALPHABETICALLY_ASCENDING_FIRST_NAME';

    case ALPHABETICALLY_DESCENDING_FIRST_NAME = 'ALPHABETICALLY_DESCENDING_FIRST_NAME';

    case ALPHABETICALLY_ASCENDING_LAST_NAME = 'ALPHABETICALLY_ASCENDING_LAST_NAME';

    case ALPHABETICALLY_DESCENDING_LAST_NAME = 'ALPHABETICALLY_DESCENDING_LAST_NAME';
}
