export function useExportTabEnums() {
    const
        PDF_CALENDAR_EXPORT = 'PDF_CALENDAR_EXPORT',
        PDF_MONTHLY_CALENDAR_EXPORT = 'PDF_MONTHLY_CALENDAR_EXPORT',
        PDF_SHIFT_PLAN_EXPORT = 'PDF_SHIFT_PLAN_EXPORT',
        EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT = 'EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT',
        EXCEL_EVENT_LIST_EXPORT = 'EXCEL_EVENT_LIST_EXPORT',
        EXCEL_CALENDAR_EXPORT = 'EXCEL_CALENDAR_EXPORT',
        EXCEL_WORK_TIME_OVERVIEW_EXPORT = 'EXCEL_WORK_TIME_OVERVIEW_EXPORT',
        EXCEL_CRAFT_DISTRIBUTION_EXPORT = 'EXCEL_CRAFT_DISTRIBUTION_EXPORT',
        EXCEL_PROJECT_ROLE_MATRIX_EXPORT = 'EXCEL_PROJECT_ROLE_MATRIX_EXPORT',
        PDF_DAILY_PROJECT_SHIFT_PLAN_EXPORT = 'PDF_DAILY_PROJECT_SHIFT_PLAN_EXPORT',
        EXCEL_SHIFT_PERSONNEL_PLAN_EXPORT = 'EXCEL_SHIFT_PERSONNEL_PLAN_EXPORT',
        PDF_SEASON_SCHEDULE_EXPORT = 'PDF_SEASON_SCHEDULE_EXPORT';

    return {
        PDF_CALENDAR_EXPORT,
        PDF_MONTHLY_CALENDAR_EXPORT,
        PDF_SHIFT_PLAN_EXPORT,
        EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT,
        EXCEL_EVENT_LIST_EXPORT,
        EXCEL_CALENDAR_EXPORT,
        EXCEL_WORK_TIME_OVERVIEW_EXPORT,
        EXCEL_CRAFT_DISTRIBUTION_EXPORT,
        EXCEL_PROJECT_ROLE_MATRIX_EXPORT,
        PDF_DAILY_PROJECT_SHIFT_PLAN_EXPORT,
        EXCEL_SHIFT_PERSONNEL_PLAN_EXPORT,
        PDF_SEASON_SCHEDULE_EXPORT
    };
}
