export function useExportTabEnums() {
    const
        PDF_CALENDAR_EXPORT = 'PDF_CALENDAR_EXPORT',
        EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT = 'EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT',
        EXCEL_EVENT_LIST_EXPORT = 'EXCEL_EVENT_LIST_EXPORT',
        EXCEL_CALENDAR_EXPORT = 'EXCEL_CALENDAR_EXPORT';

    return {
        PDF_CALENDAR_EXPORT,
        EXCEL_BUDGET_BY_BUDGET_DEADLINE_EXPORT,
        EXCEL_EVENT_LIST_EXPORT,
        EXCEL_CALENDAR_EXPORT
    };
}
