<?php

namespace App\Enums;

enum BudgetTypesEnum : string
{
    case BUDGET_TYPE_COST = 'BUDGET_TYPE_COST';
    case BUDGET_TYPE_EARNING = 'BUDGET_TYPE_EARNING';


    case BUDGET_VERIFIED_TYPE_NOT_VERIFIED = 'BUDGET_VERIFIED_TYPE_NOT_VERIFIED';
    case BUDGET_VERIFIED_TYPE_CLOSED = 'BUDGET_VERIFIED_TYPE_CLOSED';
    case BUDGET_VERIFIED_TYPE_REQUESTED = 'BUDGET_VERIFIED_TYPE_REQUESTED';

}
