<?php

namespace App\Enums;

enum NotificationConstEnum: string
{
    case NOTIFICATION_ROOM_REQUEST = 'ROOM_REQUEST';
    case NOTIFICATION_CONFLICT = 'NOTIFICATION_CONFLICT';
    case NOTIFICATION_EVENT_CHANGED = 'NOTIFICATION_EVENT_CHANGED';
    case NOTIFICATION_LOUD_ADJOINING_EVENT = 'NOTIFICATION_LOUD_ADJOINING_EVENT';
    case NOTIFICATION_UPSERT_ROOM_REQUEST = 'NOTIFICATION_UPSERT_ROOM_REQUEST';
    case NOTIFICATION_REMINDER_ROOM_REQUEST = 'NOTIFICATION_REMINDER_ROOM_REQUEST';
    case NOTIFICATION_ROOM_CHANGED = 'NOTIFICATION_ROOM_CHANGED';
    case NOTIFICATION_NEW_TASK = 'NOTIFICATION_NEW_TASK';
    case NOTIFICATION_TASK_REMINDER = 'TASK_REMINDER';
    case NOTIFICATION_TASK_CHANGED = 'TASK_CHANGED';
    case NOTIFICATION_PROJECT = 'NOTIFICATION_PROJECT';
    case NOTIFICATION_TEAM = 'NOTIFICATION_TEAM';
}
