<?php

namespace App\Enums;

class NotificationConstEnum
{
    public const NOTIFICATION_ROOM_REQUEST = 'ROOM_REQUEST';
    public const NOTIFICATION_EVENT = 'NOTIFICATION_EVENT';
    public const NOTIFICATION_BLOCKER = 'NOTIFICATION_BLOCKER';
    public const NOTIFICATION_CONFLICT = 'NOTIFICATION_CONFLICT';
    public const NOTIFICATION_PROJECT = 'NOTIFICATION_PROJECT';
    public const NOTIFICATION_SIMPLE = 'NOTIFICATION_SIMPLE';
    public const NOTIFICATION_TASK = 'NOTIFICATION_TASK';
    public const NOTIFICATION_ROOM = 'NOTIFICATION_ROOM';
    public const NOTIFICATION_TEAM = 'NOTIFICATION_TEAM';
}
